model:
  checkpoint_file: "/n/home01/twongjirad/larmae/arxiv/celestial-disco-29/checkpoint.larmae.270000th.tar"
  weight_by_model: True
  nonzero_pixel_threshold: -0.2
training_params:
  start_iter: 0
  num_iters: 100000
  iters_per_checkpoint: 10000
  iter_per_log: 10
  log_wandb: False
  wandb_project: "larmae-dev"
larmaeDataloader:
  batch_size: 64
  num_workers: 1
larmaeDataset:
#  files:
#    - /cluster/tufts/wongjiradlabnu/twongj01/larmae/dataprep/data/mcc9_v29e_dl_run3_G1_extbnb_dlana/larmaedata_run3extbnb_0000.root
#    - /n/home01/twongjirad/mcc9_v29e_dl_run3_G1_extbnb_dlana/train/larmaedata_run3extbnb_0000.root
#    - /n/home01/twongjirad/mcc9_v29e_dl_run3_G1_extbnb_dlana/train/larmaedata_run3extbnb_*.root
#    - /n/holystore01/LABS/iaifi_lab/Users/twongjirad//mcc9_v29e_dl_run3_G1_extbnb_dlana/train/larmaedata_run3extbnb_*.root
#    - larmaedata_run3extbnb_0000.root
  filelist: "/n/home01/twongjirad/larmae/mcc9_v29e_dl_run3_G1_extbnb_dlana.list"
  crop_size: 512
  adc_threshold: 10.0
  min_crop_pixels: 1000
  vector_index: 0
  use_old_root2numpy: True